### ISSUE TITLE
Will this work on a Snapdragon 685? 

### ISSUE THREAD

**Issue by ImmortalSaul** [rakarmp/DragonBoost#12]

**Comment by rakarmp** [comment]
Work fine

**Comment by ImmortalSaul** [comment]
So this shouldn't make a bootloop and no display?

**Comment by rakarmp** [comment]
> So this shouldn't make a bootloop and no display?

yes i guarantee that

**Comment by ImmortalSaul** [comment]
> > So this shouldn't make a bootloop and no display?
> 
> yes i guarantee that

I will test it later

**Comment by RiProG-id** [comment]
@ImmortalSaul Hello

**Comment by RiProG-id** [comment]
@RiProG-id Woy

**Comment by ImmortalSaul** [comment]
> @ImmortalSaul Hello

Hello?

**Comment by ImmortalSaul** [comment]
Im surprised, it worked

**Comment by rakarmp** [comment]
> Im surprised, it worked

Selamat

**Comment by ImmortalSaul** [comment]
Okay i feel no difference of performance
