### ISSUE TITLE
kernelsu

### ISSUE THREAD

**Issue by Hamood111** [rakarmp/DragonBoost#4]
thanks for this beautiful module I was using it on magisk but now I'm using kernelsu is it works or not yet maybe the next update

**Comment by rakarmp** [comment]
Yes, kernelsu should work well too

**Comment by rakarmp** [comment]
sorry maybe for this project I will stop temporarily in this version there will be no latest version for the next because maybe I see out there there are already many modules that have the same function but only different names.

**Comment by Hamood111** [comment]
> sorry maybe for this project I will stop temporarily in this version there will be no latest version for the next because maybe I see out there there are already many modules that have the same function but only different names.

it's a beautiful module even if I don't agree with u about there's a lot of modules have the same function cuz Dragonboost are different, all of them raise the core frequency but your module preserves battery life including Google services drain feature, without affecting processor performance which is good thing but in the end it's your decision and I respect it thank u rakarmp for all beautiful work ❤️

**Comment by rakarmp** [comment]
yes you're welcome
