### ISSUE TITLE
Bootloop on a52s (Vulkan Supported)

### ISSUE THREAD

**Issue by hiru12** [rakarmp/DragonBoost#5]
As soon as I installed the module and rebooted, my device bootlooped.
I'm just glad I can disable the module via TWRP.

I don't know what causes it, I don't know how to record a log hlwhen my device is in a loop.

I'm using 1.3 btly the way.

**Comment by hiru12** [comment]
Does the module only detects up to 6GB RAM? I have 8 GB RAM.

I found the log and it only says this 2 times
- Pengaturan heap Dalvik VM telah diperbarui.

**Comment by rakarmp** [comment]
Maybe the cause is in the dalvik VM heap settings that do not match the ram capacity you have, and indeed even if it is suitable it will not definitely run perfectly because basically dalvik heap has been determined by the smartphone manufacturer.

**Comment by rakarmp** [comment]
So to organize it all there are certain limits so that it can run as expected

**Comment by hiru12** [comment]
So, if I remove the script for  dalvik vm on post.fs, it might fix the issue? 

I'll try this next time.
