### ISSUE TITLE
Play Services disabled

### ISSUE THREAD

**Issue by Lourindograu** [rakarmp/DragonBoost#7]
Every time I restart my phone and unlock it, several notifications appear from Google apps saying that it doesn't work without Play Services, there is a way to activate it but it happens every time I restart.

**Comment by rakarmp** [comment]
> Every time I restart my phone and unlock it, several notifications appear from Google apps saying that it doesn't work without Play Services, there is a way to activate it but it happens every time I restart.

Thank you and apologize in advance, you have said that there is a Gplay Service problem, I will solve it as soon as possible.

**Comment by rakarmp** [comment]
are there any other problems, tell me here

**Comment by rakarmp** [comment]
are there any other problems, tell me here

**Comment by rakarmp** [comment]
Thank you for your attention, I will close this issue.
