### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [rakarmp/DragonBoost#8]
Thanks for providing your module with its code! Can you please say what license it is put under? If unsure, an overview for FOSS licenses can be [found here](https://spdx.org/licenses/). Ideally pick one that's approved as FOSS license by OSI/FSF. Thanks in advance!

**Comment by rakarmp** [comment]
> Thanks for providing your module with its code! Can you please say what license it is put under? If unsure, an overview for FOSS licenses can be [found here](https://spdx.org/licenses/). Ideally pick one that's approved as FOSS license by OSI/FSF. Thanks in advance!

Thank you for contacting me about licensing. I am glad you are interested in my module. I have chosen to use the [MIT](https://github.com/rakarmp/DragonBoost/blob/master/LICENSE) license which is an open source license approved by the Open Source Initiative (OSI) and the Free Software Foundation (FSF). You can find the full text of this license in the LICENSE file included in the repository. Hope this helps, and I hope you enjoy using and contributing to this module!

**Comment by rakarmp** [comment]
Maybe I've finished this issue, so I'll close this issue, thank you.

**Comment by IzzySoft** [comment]
Thanks, that looks fine! Last question: would you bother providing an `update.json` as well? Currently it's even impossible to construct the download URL from `module.prop` as there `versionName` has a suffix that's not part of the tag name. Dropping that ` TRYM` suffix it would be possible using `https://github.com/rakarmp/DragonBoost/releases/download/<versionName>/DragonBoost<versionName>.zip` – but a proper `update.json` would be preferable :wink:

**Comment by rakarmp** [comment]
I will try, and sorry if I am late in responding, I lack tools, namely a laptop, because my laptop is damaged due to the disaster that befell me, so I am less productive from last year to today, I hope you understand.

**Comment by IzzySoft** [comment]
Sad to hear about disaster – my sympathies, and I hope your situation will improve soon!

Thanks for adding the `update.json`! Unfortunately, the `zipURL` gives an error 400 (guess the path lacks the branch?). Maybe that should rather be `https://github.com/rakarmp/DragonBoost/raw/master/install.zip` or, which also works, `https://raw.githubusercontent.com/rakarmp/DragonBoost/master/install.zip`?

**Comment by rakarmp** [comment]
@IzzySoft I will try changing the path.

**Comment by IzzySoft** [comment]
Just saw you've edited the `update.json`, thanks – works now! Added your module to my [Magisk Repo](https://apt.izzysoft.de/magisk) now, where it will show up in about an hour (with the next sync).

**Comment by rakarmp** [comment]
@IzzySoft Great to hear!,Thanks for adding my module to your Magisk Repo!"

**Comment by IzzySoft** [comment]
Updates will be pulled automatically (though currently still on irregular intervals; that repo-util used for this is still a bit shaky so I have to watch it, cannot yet put it to a cron job or the like).

**Comment by rakarmp** [comment]
@IzzySoft I understand, no problem. I appreciate your efforts to keep things up to date.
