### ISSUE TITLE
2.7  continuous soft reboot

### ISSUE THREAD

**Issue by Ajhutchinson** [rakarmp/DragonBoost#9]
Had to uninstall due to causing a soft reboot bootloader, fully boots then goes back to boot animation, repeats.

**Comment by nuuwy0** [comment]
Any Logs from Logcat??

**Comment by rakarmp** [comment]
> Had to uninstall due to causing a soft reboot bootloader, fully boots then goes back to boot animation, repeats.

I've uploaded 2.7.1 hopefully that will resolve this issue

**Comment by Ajhutchinson** [comment]
No issues that I've encountered with the new update, thankyou bud 🙏

**Comment by rakarmp** [comment]
@Ajhutchinson Thank you for your feedback
